# Generated by Django 6.0.3 on 2026-03-18 02:29

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código da Estação')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('basin', models.CharField(db_index=True, max_length=255, verbose_name='Bacia Hidrográfica')),
                ('state', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Estado')),
                ('city', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Município')),
                ('station_type', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Tipo de Estação')),
                ('operator', models.CharField(blank=True, max_length=255, null=True, verbose_name='Órgão Operador')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('missing_percentage', models.FloatField(blank=True, null=True, verbose_name='% de Falhas')),
                ('is_active', models.BooleanField(default=True, help_text='Estações inativas não recebem novos dados das agências.', verbose_name='Estação Ativa')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('last_historical_sync', models.DateTimeField(blank=True, help_text='Define quando o robô de background baixou a série temporal desta estação pela última vez.', null=True, verbose_name='Última Sincronização Histórica')),
                ('latest_raw_data_date', models.DateField(blank=True, help_text='Cursor Delta: Maior data de precipitação já extraída para não reprocessar o passado.', null=True, verbose_name='Último Dado Bruto da ANA')),
                ('last_gap_fill_date', models.DateField(blank=True, help_text='Cursor Matemático: Ponteiro para a Fase 3 saber a partir de que data deve iniciar o preenchimento (IDW/Thiessen).', null=True, verbose_name='Último Preenchimento de Falha')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('is_active', True)), fields=['is_active'], name='active_stations_idx'), models.Index(fields=['state', 'station_type'], name='state_type_idx'), models.Index(fields=['missing_percentage'], name='quality_idx'), models.Index(fields=['last_historical_sync'], name='historical_sync_idx'), models.Index(fields=['latest_raw_data_date'], name='latest_raw_idx'), models.Index(fields=['last_gap_fill_date'], name='last_gap_idx')],
            },
        ),
        migrations.CreateModel(
            name='RawPrecipitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da Medição')),
                ('measured_value', models.FloatField(blank=True, null=True, verbose_name='Valor Medido (mm)')),
                ('origin', models.CharField(max_length=50, verbose_name='Origem dos Dados')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precipitations', to='ingestion.station')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'station'], name='ingestion_r_date_4aac74_idx'), django.contrib.postgres.indexes.BrinIndex(fields=['date'], name='brin_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('measured_value__gte', 0.0), ('measured_value__isnull', True), _connector='OR'), name='check_valid_precipitation')],
                'unique_together': {('station', 'date', 'origin')},
            },
        ),
    ]
