services:
  db:
    image: postgis/postgis:15-3.3
    container_name: project_project_hidrodata_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: project_hidrodata_redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: project_hidrodata_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  celery_user:
    build: .
    container_name: project_hidrodata_celery_user
    command: celery -A config_project worker -Q user_demand,celery -c 3 -l INFO
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  celery_auto:
    build: .
    container_name: project_hidrodata_celery_auto
    command: celery -A config_project worker -Q auto_sync -c 2 -l INFO
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgis_data: